const portalImage = 'images/ChatGPT%20Image%2019%20de%20ago.%20de%202026,%2023_48_14.png';
const escapeHtml = value => String(value || '').replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]));
const request = (url, options = {}) => fetch(url, { headers: { 'Content-Type': 'application/json' }, ...options }).then(async response => { const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Operação não realizada.'); return body; });
function renderNews(news) { const grid = document.querySelector('#news-grid'); grid.innerHTML = news.length ? news.slice(0, 6).map(item => `<article class="news-card"><div class="news-card-image"><img src="${escapeHtml(item.image || portalImage)}" alt="Imagem institucional do portal" loading="lazy"></div><div class="news-card-body"><span class="tag">ASCOM / comunicado</span><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.summary || item.description)}</p><span class="news-date">${escapeHtml(item.date || '')}</span></div></article>`).join('') : '<div class="empty-state">Nenhum comunicado publicado no momento.</div>'; }
function renderCollection(id, items, empty) { const target = document.querySelector(id); if (!target) return; target.innerHTML = items.length ? items.slice(0, 6).map(item => `<article class="data-card"><span class="status">${escapeHtml(item.status || 'Publicado')}</span><h3>${escapeHtml(item.title || item.subject)}</h3><p>${escapeHtml(item.description || item.summary)}</p><span class="news-date">${escapeHtml(item.date || '')}</span></article>`).join('') : `<div class="empty-state">${empty}</div>`; }
function orgBox(item) { return `<div class="org-box"><span>Nível ${escapeHtml(item.tier ?? '')}</span><strong>${escapeHtml(item.title)}</strong><p>${escapeHtml(item.description)}</p></div>`; }
function renderOrgTree(items) { const tree = document.querySelector('#org-tree'); if (!tree) return; if (!items.length) { tree.innerHTML = '<li><div class="empty-state">Estrutura organizacional ainda não publicada.</div></li>'; return; } const sorted = [...items].sort((a, b) => (a.tier || 0) - (b.tier || 0)); const root = sorted.find(item => item.tier === 1) || sorted[0]; const tier2 = sorted.filter(item => item.tier === 2); const tier3 = sorted.filter(item => item.tier === 3 || (!item.tier && item !== root)); if (!tier2.length) { tree.innerHTML = `<li>${orgBox(root)}</li>`; return; } const tier2Html = tier2.map((item, index) => { const isLast = index === tier2.length - 1; const nested = isLast && tier3.length ? `<ul>${tier3.map(node => `<li>${orgBox(node)}</li>`).join('')}</ul>` : ''; return `<li>${orgBox(item)}${nested}</li>`; }).join(''); tree.innerHTML = `<li>${orgBox(root)}<ul>${tier2Html}</ul></li>`; }
function renderMedals(items) { const list = document.querySelector('#medal-rank'); if (!list) return; if (!items.length) { list.innerHTML = '<li class="empty-state">Nenhuma condecoração publicada.</li>'; return; } const sorted = [...items].sort((a, b) => (a.tier || 0) - (b.tier || 0)); list.innerHTML = sorted.map(item => `<li><div class="medal-body"><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.description)}</p></div></li>`).join(''); }
async function loadPublicData() { try { const [news, editais, resultados, organograma, medalhas] = await Promise.all([request('/api/news'), request('/api/editais'), request('/api/resultados'), request('/api/organograma'), request('/api/medalhas')]); renderNews(news); renderCollection('#editais-grid', editais, 'Nenhum edital aberto no momento.'); renderCollection('#results-list', resultados, 'Nenhum resultado publicado.'); renderOrgTree(organograma); renderMedals(medalhas); } catch { document.querySelector('#news-grid').innerHTML = '<div class="empty-state">O serviço de comunicação está temporariamente indisponível.</div>'; } }
const portalTabs = document.querySelector('.portal-tabs');
portalTabs.innerHTML = `<button class="portal-tab active" data-view="operacionais">OPERACIONAIS</button><div class="portal-dropdown"><button class="portal-tab" data-view="institucional">INSTITUCIONAL ▼</button><div class="portal-menu"><button data-view="organograma">Organograma</button><button data-view="institucional">PF em números</button><button data-view="medalhas">Ordem do Mérito</button><button data-view="unidades">Unidades especiais</button></div></div><div class="portal-dropdown"><button class="portal-tab" data-view="servicos">PORTAL DE SERVIÇOS ▼</button><div class="portal-menu"><button data-view="editais">Editais e concursos</button><button data-view="cidadao">Serviços ao cidadão</button><button data-view="corregedoria">Canais de atendimento</button></div></div><div class="portal-dropdown"><button class="portal-tab" data-view="editais">EDITAIS ▼</button><div class="portal-menu"><button data-view="editais">Edital aberto</button><button data-view="resultados">Resultados do edital</button></div></div><div class="portal-dropdown"><button class="portal-tab" data-view="corregedoria">CORREGEDORIA ▼</button><div class="portal-menu"><button data-view="corregedoria">Denúncia formal</button><button data-view="comunica">Comunica PF (anônimo)</button></div></div><button class="portal-tab" data-view="noticias">ASCOM</button><button class="portal-tab" data-view="contato">FALE CONOSCO</button><button class="portal-tab" data-view="superintendencia">SUPERINTENDÊNCIA</button>`;
document.querySelector('.brand-mark').outerHTML = '<img class="brand-logo" src="images/pf.jpg" alt="Polícia Federal" onerror="this.onerror=null;this.src=\'images/pf-logo.svg\'">';
document.querySelector('footer span:last-child').textContent = 'Ambiente demonstrativo · ASCOM · Corregedoria';
document.querySelector('.system-card').innerHTML = '<div class="monitor-head"><span>PF_MONITOR / CORE</span><strong>● LINKED</strong></div><div class="monitor-command"><span>pf@secure-node:~$</span> systemctl status federal-net</div><div class="monitor-state"><i></i><span>ACTIVE</span><b>PROTEGIDA</b></div><div class="monitor-metrics"><div><span>SYNC</span><strong>99.98%</strong><em><i></i><i></i><i></i><i></i><i></i></em></div><div><span>LATENCY</span><strong>08ms</strong><em><i></i><i></i><i></i></em></div><div><span>LOAD</span><strong>24%</strong><em><i></i><i></i></em></div></div><div class="monitor-log"><p><b>01</b> [ok] encrypted channel ready</p><p><b>02</b> [ok] operational feed synced</p><p><b>03</b> [--] console standby<span>_</span></p></div><button id="connection-check" class="check-button">Run connection check <span>↗</span></button>';
document.querySelector('#connection-check')?.addEventListener('click', event => { event.currentTarget.textContent = 'Conexão verificada ✓'; });
document.querySelector('#result-form')?.addEventListener('submit', async event => { event.preventDefault(); const message = document.querySelector('#result-message'); const token = document.querySelector('#result-token').value.trim().toLowerCase(); if (!token) return; try { const results = await request('/api/resultados'); const match = results.find(item => String(item.token || '').toLowerCase() === token); message.textContent = match ? `Resultado encontrado: ${match.title}. ${match.description}` : 'Nenhum resultado localizado para este identificador.'; } catch (error) { message.textContent = error.message; } });
document.querySelector('#complaint-form')?.addEventListener('submit', async event => { event.preventDefault(); const message = document.querySelector('#complaint-message'); try { const result = await request('/api/denuncias', { method: 'POST', body: JSON.stringify({ subject: document.querySelector('#complaint-subject').value, contact: document.querySelector('#complaint-contact').value, description: document.querySelector('#complaint-description').value }) }); event.target.reset(); message.textContent = `Denúncia recebida. Protocolo: ${result.id}`; } catch (error) { message.textContent = error.message; } });
document.querySelector('#complaint-track-form')?.addEventListener('submit', async event => { event.preventDefault(); const message = document.querySelector('#complaint-track-message'); const protocol = document.querySelector('#complaint-protocol').value.trim(); try { const result = await request(`/api/denuncias/${encodeURIComponent(protocol)}`); message.textContent = `Protocolo ${result.id}: ${result.status}. Recebido em ${new Date(result.createdAt).toLocaleDateString('pt-BR')}.`; } catch (error) { message.textContent = error.message; } });

function submitRequest(formId, tipo, fields) { document.querySelector(formId)?.addEventListener('submit', async event => { event.preventDefault(); const message = document.querySelector('#request-message'); try { const payload = { tipo }; Object.entries(fields).forEach(([key, selector]) => { payload[key] = document.querySelector(selector)?.value || ''; }); const result = await request('/api/solicitacoes', { method: 'POST', body: JSON.stringify(payload) }); event.target.reset(); message.textContent = `Solicitação registrada. Protocolo: ${result.id}`; } catch (error) { message.textContent = error.message; } }); }
submitRequest('#request-porte-form', 'porte', { nome: '#porte-nome', passaporte: '#porte-doc', contato: '#porte-contato', descricao: '#porte-descricao' });
submitRequest('#request-documentos-form', 'documentos', { nome: '#documentos-nome', passaporte: '#documentos-doc', contato: '#documentos-contato', descricao: '#documentos-descricao' });
submitRequest('#request-reab-form', 'reabilitacao', { nome: '#reab-nome', passaporte: '#reab-doc', contato: '#reab-contato', descricao: '#reab-descricao' });
document.querySelector('#request-reab-anexo-form')?.addEventListener('submit', async event => { event.preventDefault(); const message = document.querySelector('#request-message'); try { const anexos = [document.querySelector('#reab-anexo-link1').value, document.querySelector('#reab-anexo-link2').value]; const result = await request('/api/solicitacoes', { method: 'POST', body: JSON.stringify({ tipo: 'reabilitacao', nome: document.querySelector('#reab-anexo-nome').value, passaporte: document.querySelector('#reab-anexo-processo').value, descricao: `Anexos vinculados ao processo ${document.querySelector('#reab-anexo-processo').value}`, anexos }) }); event.target.reset(); message.textContent = `Anexos enviados. Protocolo: ${result.id}`; } catch (error) { message.textContent = error.message; } });
document.querySelector('#request-track-form')?.addEventListener('submit', async event => { event.preventDefault(); const message = document.querySelector('#request-track-message'); const protocol = document.querySelector('#request-protocol').value.trim(); try { const result = await request(`/api/solicitacoes/${encodeURIComponent(protocol)}`); message.textContent = `Protocolo ${result.id}: ${result.status}. Recebido em ${new Date(result.createdAt).toLocaleDateString('pt-BR')}.`; } catch (error) { message.textContent = error.message; } });

document.querySelector('#comunica-form')?.addEventListener('submit', async event => { event.preventDefault(); const message = document.querySelector('#comunica-message'); try { const anexos = [document.querySelector('#comunica-img1').value, document.querySelector('#comunica-img2').value, document.querySelector('#comunica-video').value]; const result = await request('/api/denuncias', { method: 'POST', body: JSON.stringify({ subject: 'Comunicação sigilosa', description: document.querySelector('#comunica-relato').value, contact: `${document.querySelector('#comunica-codinome').value} ${document.querySelector('#comunica-telefone').value}`.trim(), alvo: document.querySelector('#comunica-alvo').value, anonima: true, anexos }) }); event.target.reset(); message.textContent = `Informação recebida com sigilo. Protocolo: ${result.id}`; } catch (error) { message.textContent = error.message; } });

document.querySelector('#contato-form')?.addEventListener('submit', async event => { event.preventDefault(); const message = document.querySelector('#contato-message'); try { const result = await request('/api/solicitacoes', { method: 'POST', body: JSON.stringify({ tipo: 'contato', nome: document.querySelector('#contato-nome').value, contato: document.querySelector('#contato-email').value, descricao: document.querySelector('#contato-descricao').value }) }); event.target.reset(); message.textContent = `Mensagem enviada. Protocolo: ${result.id}`; } catch (error) { message.textContent = error.message; } });

loadPublicData();
function activateView(view) {
	const validViews = ['operacionais', 'institucional', 'noticias', 'editais', 'resultados', 'corregedoria', 'servicos', 'superintendencia', 'organograma', 'medalhas', 'cidadao', 'comunica', 'contato', 'unidades'];
	const normalizedView = validViews.includes(view) ? view : 'operacionais';
	document.querySelectorAll('.portal-view').forEach(section => section.classList.toggle('active', section.id === normalizedView));
	document.querySelectorAll('.portal-tab').forEach(tab => tab.classList.toggle('active', tab.dataset.view === normalizedView));
	history.replaceState(null, '', `#${normalizedView}`);
	window.scrollTo({ top: 0, behavior: 'smooth' });
}
document.querySelectorAll('.portal-tab, .portal-menu button, .jump-tab').forEach(control => control.addEventListener('click', () => activateView(control.dataset.view)));
activateView(location.hash.slice(1) || 'operacionais');
